import type { Metadata, Viewport } from "next";
import Navbar from "@/components/navbar";
import BottomBar from "@/components/buttombar";

export const metadata: Metadata = {
  applicationName: "Write For Me",
  manifest: "/manifest.json",
  title: "Write For Me",
  description: "Generated by create Write For Me",
};

export const viewport: Viewport = {
  themeColor: "#070012",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className=" w-full">
      <Navbar />
      <div className="mt-[80px] relative w-full min-h-screen ">
        {children}
      </div>
      <BottomBar />
    </main>
  );
}
