import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import QuaryClient from "@/provider/QuaryClient";
import ErrorBoundary from "@/components/errorBoundary";

export const metadata: Metadata = {
  title: "Write For Other",
  description: "Generated by create Write For Other",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QuaryClient >
          <Toaster position="top-right"reverseOrder={false} />
          <div className=" relative w-full min-h-screen ">
            {/* {children} */}
            {/* <ErrorBoundary> */}
              {children}
            {/* </ErrorBoundary> */}

          </div>
        </QuaryClient>
      </body>
    </html>
  );
}
