import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import BottomBar from "@/components/buttombar";

export const metadata: Metadata = {
  title: "Write For Other",
  description: "Generated by create Write For Other",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className=" w-full">
      <Navbar />
      <div className="mt-[100px] relative w-full min-h-screen ">
        {children}
      </div>
      <BottomBar />
    </main>
  );
}
